[Desktop Entry]
Type=Tag
URL=CONCEPTDESIGN_MyPaint
ResourceType=paintoppresets
Name=CONCEPTDESIGN_MyPaint
Comment=CONCEPTDESIGN_MyPaint
Default Resources=CONCEPTDESIGN_Eraser.kpp,CONCEPTDESIGN_InkBrush_and_eraser.kpp,CONCEPTDESIGN_Marker_Big_BG.kpp,CONCEPTDESIGN_Marker_Blender_Marker.kpp,CONCEPTDESIGN_Marker_Dark_Marker.kpp,CONCEPTDESIGN_Marker_Draw_1.kpp,CONCEPTDESIGN_Marker_Draw_2.kpp,CONCEPTDESIGN_Marker_Light_Marker.kpp,CONCEPTDESIGN_Marker_Medium_Marker.kpp,CONCEPTDESIGN_Marker_Permanent_Black.kpp,CONCEPTDESIGN_Marker_Wide_Big.kpp,CONCEPTDESIGN_Marker_Wide_small.kpp,CONCEPTDESIGN_Pen_04_pen.kpp,CONCEPTDESIGN_Pen_08_pen.kpp,CONCEPTDESIGN_Pen_Penbrush.kpp,CONCEPTDESIGN_Pen_Text_Marker.kpp,CONCEPTDESIGN_Eraser.kpp,CONCEPTDESIGN_InkBrush_and_eraser.kpp,CONCEPTDESIGN_Marker_Big_BG.kpp,CONCEPTDESIGN_Marker_Blender_Marker.kpp,CONCEPTDESIGN_Marker_Dark_Marker.kpp,CONCEPTDESIGN_Marker_Draw_1.kpp,CONCEPTDESIGN_Marker_Draw_2.kpp,CONCEPTDESIGN_Marker_Light_Marker.kpp,CONCEPTDESIGN_Marker_Medium_Marker.kpp,CONCEPTDESIGN_Marker_Permanent_Black.kpp,CONCEPTDESIGN_Marker_Wide_Big.kpp,CONCEPTDESIGN_Marker_Wide_small.kpp,CONCEPTDESIGN_Pen_04_pen.kpp,CONCEPTDESIGN_Pen_08_pen.kpp,CONCEPTDESIGN_Pen_Penbrush.kpp,CONCEPTDESIGN_Pen_Text_Marker.kpp
