[Desktop Entry]
Type=Tag
URL=KAERHON_MyPaint
ResourceType=paintoppresets
Name=KAERHON_MyPaint
Comment=KAERHON_MyPaint
Default Resources=KAERHON_a_extreme_round_l.kpp,KAERHON_a_flat_bar_l.kpp,KAERHON_a_inkster_l.kpp,KAERHON_b_ink-slowline_s.kpp,KAERHON_b_ink_slow_s.kpp,KAERHON_c_Smear_sm.kpp,KAERHON_c_paint_barrr_sm.kpp,KAERHON_c_paint_radius_2_sm.kpp,KAERHON_c_paint_sm.kpp,KAERHON_c_wet_paint_sm.kpp,KAERHON_d_Dirty_Transparent_sk.kpp,KAERHON_d_Sketcher2_sk.kpp,KAERHON_d_airsmudgeultimate_sk.kpp,KAERHON_d_classic_sk.kpp,KAERHON_e_Airbrush_a.kpp,KAERHON_e_airbruch_press_a.kpp,KAERHON_e_airsmudge_a.kpp,KAERHON_f_classicroundblock_static_c.kpp,KAERHON_f_fill_c.kpp,KAERHON_a_extreme_round_l.kpp,KAERHON_a_flat_bar_l.kpp,KAERHON_a_inkster_l.kpp,KAERHON_b_ink-slowline_s.kpp,KAERHON_b_ink_slow_s.kpp,KAERHON_c_Smear_sm.kpp,KAERHON_c_paint_barrr_sm.kpp,KAERHON_c_paint_radius_2_sm.kpp,KAERHON_c_paint_sm.kpp,KAERHON_c_wet_paint_sm.kpp,KAERHON_d_Dirty_Transparent_sk.kpp,KAERHON_d_Sketcher2_sk.kpp,KAERHON_d_airsmudgeultimate_sk.kpp,KAERHON_d_classic_sk.kpp,KAERHON_e_Airbrush_a.kpp,KAERHON_e_airbruch_press_a.kpp,KAERHON_e_airsmudge_a.kpp,KAERHON_f_classicroundblock_static_c.kpp,KAERHON_f_fill_c.kpp
